apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-in-kubernetes-fpm
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: registry.gitlab.com/victorjuniorrb/laravel-in-kubernetes/cli:v0.0.1
          command:
            - php
          # neste exemplo é populada a base com dados iniciais, 
          # em produção não usar o seed
          args:
            - artisan
            - migrate:fresh
            - --seed
          # args:
          #   - artisan
          #   - migrate
          #   - --force
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes
      containers:
        - name: fpm
          image: registry.gitlab.com/victorjuniorrb/laravel-in-kubernetes/fpm_server:v0.0.1
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes
          resources:
            requests:
              memory: 64Mi
              cpu: 255m
            limits:
              memory: 128Mi
              cpu: 500m