# Subir o serviço de cron como sendo um container
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: laravel-in-kubernetes-cron
#   labels:
#     tier: backend
#     layer: cron
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       tier: backend
#       layer: cron
#   template:
#     metadata:
#       labels:
#         tier: backend
#         layer: cron
#     spec:
#       containers:
#         - name: cron
#           image: registry.gitlab.com/victorjuniorrb/laravel-in-kubernetes/cron:v0.0.1
#           envFrom:
#             - configMapRef:
#                 name: laravel-in-kubernetes
#             - secretRef:
#                 name: laravel-in-kubernetes
#           resources:
#             requests:
#               memory: 64Mi
#               cpu: 255m
#             limits:
#               memory: 128Mi
#               cpu: 500m