services:
    laravel:
        image: ${DOCKER_IMAGE}:${VERSION}
        environment:
            CONTAINER_MODE: http
            WITH_HORIZON: false
            WITH_SCHEDULER: false
        volumes:
            - 'storage_app:/var/www/html/storage/app'
        networks:
            - frontend
            - backend
        ports:
            - 8000:8000
        depends_on:
            - redis
            - mysql
        env_file: 
            - stack.env
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "5"

    laravel_worker:
        image: ${DOCKER_IMAGE}:${VERSION}
        environment:
            CONTAINER_MODE: worker
            RUNNING_MIGRATIONS_AND_SEEDERS: true
            WORKER_COMMAND: php /var/www/html/artisan queue:work
        volumes:
            - 'storage_app:/var/www/html/storage/app'
        env_file:
            - stack.env
        networks:
            - backend
        depends_on:
            - redis
        healthcheck:
            test: ["CMD", "true"]
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "5"

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - backend
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]                
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:7-alpine'
        environment:
            TZ: America/Sao_Paulo
            ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - 'redis:/data'
        networks:
            - backend
        healthcheck:
            test: ["CMD", "redis-cli", "ping" ]
            retries: 5
            timeout: 5s

networks:
    frontend:
    backend:
volumes:
    mysql:
    redis:
    storage_app: